###
# HYPRLAND AUTOSTARTS
###

# SYSTEM
# exec-once = plymouth quit
# exec-once = /usr/local/bin/plymouth-fade
exec-once = hyprlock --immediate
exec-once = /home/MrUnknown850/.local/bin/switcher.sh

#exec-once = hyprpm reload -n
exec-once = batsignal -w 25 -c 15 -d 5 -f 80
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = uwsm app -- fcitx5 -d

exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- hypridle
exec = wl-paste --watch cliphist store
exec = uwsm app -- blueman-applet
exec = uwsm app -- wlsunset -l 21 -L 105

