--##
-- HYPRLAND AUTOSTARTS
--##

-- SYSTEM
-- exec-once = plymouth quit
-- exec-once = /usr/local/bin/plymouth-fade
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

--exec-once = hyprpm reload -n

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock --immediate")
    hl.exec_cmd("/home/MrUnknown850/.local/bin/switcher.sh")
    hl.exec_cmd("batsignal -w 25 -c 15 -d 5 -f 80")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("uwsm app -- fcitx5 -d")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("uwsm app -- hypridle")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("uwsm app -- blueman-applet")
    hl.exec_cmd("uwsm app -- wlsunset -l 21 -L 105")
end)

