-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 7

-- TODO: manual review — unknown section 'listener {' on line 13

-- TODO: manual review — unknown section 'listener {' on line 19

hl.config({
    general = {
        lock_cmd = "hyprlock",
        before_sleep_cmd = "hyprlock --no-fade-in",
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

