-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'auth {' on line 5

-- TODO: manual review — unknown section 'background {' on line 14
-- vibrancy = 0.3

-- TODO: manual review — unknown section 'label {' on line 23
-- font_family = SF Pro Rounded Medium

-- TODO: manual review — unknown section 'label {' on line 34
-- text = Wednesday, November 1

-- TODO: manual review — unknown section 'image {' on line 45

-- TODO: manual review — unknown section 'label {' on line 58

-- TODO: manual review — unknown section 'label {' on line 65

-- TODO: manual review — unknown section 'input-field {' on line 73
hl.config({
    general = {
        ignore_empty_input = true,
    },
})

