--#########################
-- HYPRLAND MASTER CONFIG #
--#########################

-- Monitors
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- Hyprland variables
local reload_fcitx5 = HOME .. "/.config/hypr/reload_fcitx5.sh"
local volume_script = HOME .. "/.config/hypr/volume"
local backlight_script = HOME .. "/.config/hypr/backlight"
local shifter = HOME .. "/.config/hypr/shift-workspace.sh"
local clipboard = "cliphist list | rofi -dmenu | cliphist decode | wl-copy"
local clear_cb = "cliphist wipe"
local terminal = "uwsm app -- kitty -d=last_reported"
local fileManager = "uwsm app -- nautilus"
local emoji = "bemoji -n"
local menu = "pkill rofi || rofi -icon-theme \"Papirus\" -show drun -run-command \"uwsm app -- {cmd}\""
local power = "pkill rofi || rofi -icon-theme \"Papirus\" -show powermenu"

-- Environment variables
hl.env("HYPRCURSOR_SIZE", "40")
hl.env("DXVK_ASYNC", "1")
hl.env("SDL_VIDEODRIVER", "wayland")

-- Other configs
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.config/hypr/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("general")
-- Source: ~/.config/hypr/windows.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windows")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/bindings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("bindings")
-- Source: ~/.config/hypr/plugins.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("plugins")
-- source = ~/.config/hypr/alt-tab.conf

