--#########################
-- HYPRLAND MASTER CONFIG #
--#########################

-- Monitors
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- Hyprland variables
local reload_fcitx5 = "$HOME/.config/hypr/reload_fcitx5.sh"
local volume_script = "$HOME/.config/hypr/volume"
local backlight_script = "$HOME/.config/hypr/backlight"
local shifter = "$HOME/.config/hypr/shift-workspace.sh"
local clipboard = "cliphist list | rofi -dmenu | cliphist decode | wl-copy"
local clear_cb = "cliphist wipe"
local terminal = "uwsm app -- kitty -d=last_reported"
local fileManager = "uwsm app -- nautilus"
local emoji = "bemoji -n"
local menu = "pkill rofi || rofi -icon-theme \"Papirus\" -show drun -run-command \"uwsm app -- {cmd}\""
local power = "pkill rofi || rofi -icon-theme \"Papirus\" -show powermenu"

mainMod = "SUPER" -- Sets "Windows" key as main modifier
  
-- Environment variables
hl.env("HYPRCURSOR_SIZE", "40")
hl.env("DXVK_ASYNC", "1")
hl.env("SDL_VIDEODRIVER", "wayland")

-- Other configs
require("modules/autostart")
require("modules/general")
require("modules/windows")
require("modules/input")
require("modules/plugins")

hl.bind(mainMod .. " + F12", hl.dsp.exec_cmd(reload_fcitx5))
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())

hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

-- QuickBar
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd(power), { release = true })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd(emoji))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(clipboard))
hl.bind(mainMod .. " + ALT + V", hl.dsp.exec_cmd(clear_cb))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))

-- Lock
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))

-- =========================================
-- =============== WORKSPACES ==============
-- =========================================

-- Layout control
hl.bind(mainMod .. " + S", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + T", hl.dsp.group.toggle())
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.group.lock_active("toggle"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen(""))
hl.bind(mainMod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + minus", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mainMod .. " + equal", hl.dsp.workspace.toggle_special("miracle"))
hl.bind(mainMod .. " + SHIFT + equal", hl.dsp.window.move({ workspace = "special:miracle" }))

hl.bind(mainMod .. " + SHIFT + I", hl.dsp.focus({ workspace = "+1" }))
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.focus({ workspace = -1 }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- ======================================
-- =============== WINDOWS ==============
-- ======================================

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
--bind = $mainMod ALT, L, changegroupactive, f
--bind = $mainMod ALT, H, changegroupactive, b

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Swaping windows.
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.swap({ direction = "d" }))

-- Resize mode
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function() 
  hl.bind("l", hl.dsp.window.resize({ x = 20, y = 0, relative=true}), { repeating = true })
  hl.bind("h", hl.dsp.window.resize({ x = -20, y = 0, relative=true}), { repeating = true })
  hl.bind("k", hl.dsp.window.resize({ x = 0, y = -20, relative=true}), { repeating = true })
  hl.bind("j", hl.dsp.window.resize({ x = 0, y =  20, relative=true}), { repeating = true })

  hl.bind("SHIFT + l", hl.dsp.window.resize({ x = 100, y = 0, relative=true}), { repeating = true })
  hl.bind("SHIFT + h", hl.dsp.window.resize({ x = -100, y = 0, relative=true}), { repeating = true })
  hl.bind("SHIFT + k", hl.dsp.window.resize({ x = 0, y = -100, relative=true}), { repeating = true })
  hl.bind("SHIFT + j", hl.dsp.window.resize({ x = 0, y =  100, relative=true}), { repeating = true })

  hl.bind("escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + SHIFT + M", hl.dsp.submap("move"))
hl.define_submap("move", function() 
  hl.bind("l", hl.dsp.window.move({ x = 20, y = 0, relative=true}), { repeating = true })
  hl.bind("h", hl.dsp.window.move({ x = -20, y = 0, relative=true}), { repeating = true })
  hl.bind("k", hl.dsp.window.move({ x = 0, y = -20, relative=true}), { repeating = true })
  hl.bind("j", hl.dsp.window.move({ x = 0, y =  20, relative=true}), { repeating = true })

  hl.bind("SHIFT + l", hl.dsp.window.move({ x = 100, y = 0, relative=true}), { repeating = true })
  hl.bind("SHIFT + h", hl.dsp.window.move({ x = -100, y = 0, relative=true}), { repeating = true })
  hl.bind("SHIFT + k", hl.dsp.window.move({ x = 0, y = -100, relative=true}), { repeating = true })
  hl.bind("SHIFT + j", hl.dsp.window.move({ x = 0, y =  100, relative=true}), { repeating = true })

  hl.bind("escape", hl.dsp.submap("reset"))
end)

-- =====================================
-- =============== OTHERS ==============
-- =====================================

hl.bind(mainMod .. " + End", hl.dsp.exec_cmd(shifter))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(volume_script .. " --inc"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(volume_script .. " --dec"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(volume_script .. " --toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(volume_script .. " --toggle-mic"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(backlight_script .. " --inc"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(backlight_script .. " --dec"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Screenshot
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -o ~/Pictures/Screenshots -m output"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -o ~/Pictures/Screenshots -m region"))

-- Hyprland specific
hl.bind(mainMod .. " + p", hl.dsp.exec_cmd("hyprlock"))
