#####################################
# HYPRLAND WINDOWS BEHAVIOUR CONFIG #
#####################################
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

# Special workspace rules
workspace = s[true], on-create-empty:[float]

# Floating rules
windowrule = float on, match:class org.fcitx.fcitx5-config-qt
windowrule = float on, match:class nemo
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class net.lutris.Lutris
windowrule = float on, match:class zoom
windowrule = float on, size (monitor_w*0.5) (monitor_h*0.5), match:class kitty
windowrule = float on, match:class ru-turikhay-tlauncher-bootstrap-Bootstrap
windowrule = float on, match:class moe.launcher.the-honkers-railway-launcher
windowrule = fullscreen on, match:class Waydroid
windowrule = float on, size (monitor_w*0.3) (monitor_h*0.4), match:title Picture-in-Picture
windowrule = float on, match:class org.gnome.seahorse.*
windowrule = float on, match:class mpv
windowrule = float on, match:class ModernGL
windowrule = float on, match:class steam

# Inhibit Idle
windowrule = idle_inhibit fullscreen, suppress_event maximize, match:class .*
windowrule = idle_inhibit always, match:class ^(ClassIn)$
windowrule = idle_inhibit always, match:class ^(firefox)$, match:title (.* - YouTube)

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
