-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind("ALT + TAB", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/alttab/enable.sh 'down'"))
hl.bind("ALT + SHIFT + TAB", hl.dsp.exec_cmd(HOME .. "/.config/hypr/scripts/alttab/enable.sh 'up'"))

-- TODO: manual review — wrap the following binds in hl.define_submap("alttab", function() ... end). The next 'submap = reset' closes the block.
hl.bind("ALT + tab", hl.dsp.send_shortcut(", tab, class:alttab"))
hl.bind("ALT + SHIFT + tab", hl.dsp.send_shortcut("shift, tab, class:alttab"))

hl.bind("ALT + ALT_L", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, return, class:alttab"), { release = true, transparent = true })
hl.bind("ALT + SHIFT + ALT_L", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, return, class:alttab"), { release = true, transparent = true })
hl.bind("ALT + Return", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, return, class:alttab"))
hl.bind("ALT + SHIFT + Return", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, return, class:alttab"))
hl.bind("ALT + escape", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, escape, class:alttab"))
hl.bind("ALT + SHIFT + escape", hl.dsp.exec_cmd(XDG_CONFIG_HOME .. "/hypr/scripts/alttab/disable.sh ; hyprctl -q dispatch sendshortcut, escape, class:alttab"))
-- (end of submap block)

hl.workspace_rule({
    workspace = "special:alttab",
    gaps_out = 0,
    gaps_in = 0,
    border_size = 0,
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        class = "alttab",
    },
    -- TODO: manual review — unmapped window rule action: "no_anim on"
    -- TODO: manual review — unmapped window rule action: "stay_focused on"
    workspace = "special:alttab",
    -- TODO: manual review — unmapped window rule action: "border_size 0"
})

hl.on("hyprland.start", function()
    hl.exec_cmd("foot --server -c " .. XDG_CONFIG_HOME .. "/foot/foot.ini")
end)

