--#####################
-- PERIPHEPAL CONTROL #
--#####################

-- Input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
    -- TODO: manual review — extra gesture field ""
})
hl.gesture({
    fingers = 4,
    direction = "vertical",
    action = "float",
    -- TODO: manual review — extra gesture field ""
})

hl.device({
    name = "genius-wireless-device-1",
    sensitivity = 1,
    accel_profile = "adaptive",
})

hl.device({
    name = "genius-wireless-device-consumer-control-1",
    sensitivity = 1,
    accel_profile = "adaptive",
})

hl.device({
    name = "logitech-wireless-receiver-mouse",
    sensitivity = 1,
    accel_profile = "flat",
})

hl.device({
    name = "usb-receiver-usb-receiver",
    sensitivity = 0,
    accel_profile = "adaptive",
})

hl.device({
    name = "tpps/2-elan-trackpoint",
    sensitivity = 0.21,
    accel_profile = "adaptive",
})

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_options = "caps:escape",
        kb_model = "",
        kb_rules = "",
        follow_mouse = 2,
        sensitivity = 0.15,
        accel_profile = "adaptive",
        touchpad = {
            disable_while_typing = false,
            natural_scroll = true,
            -- scroll_factor = 0.7
        },
    }
})

