-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  touch_gestures { ... }
]]

-- TODO: manual review — plugin section 'dynamic-cursors'. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  enabled = true
  mode = shake
  threshold = 2
  shake { ... }
  hyprcursor { ... }
]]

