--####################################
-- HYPRLAND WINDOWS BEHAVIOUR CONFIG #
--####################################
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- hl.workspace_rule({
--     workspace = "s[true]",
--     ["on-create-empty"] = "[float]",
-- })

hl.window_rule({
    match = {
        class = "org.fcitx.fcitx5-config-qt",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "nemo",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "blueman-manager",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "net.lutris.Lutris",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "zoom",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "kitty",
    },
    float = true,
    size = "(monitor_w*0.5) (monitor_h*0.5)",
})

hl.window_rule({
    match = {
        class = "ru-turikhay-tlauncher-bootstrap-Bootstrap",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "moe.launcher.the-honkers-railway-launcher",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "Waydroid",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        title = "Picture-in-Picture",
    },
    float = true,
    size = "(monitor_w*0.3) (monitor_h*0.4)",
})

hl.window_rule({
    match = {
        class = "org.gnome.seahorse.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "mpv",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "ModernGL",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "steam",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit fullscreen"
    suppress_event = "maximize",
})

hl.window_rule({
    match = {
        class = "^(ClassIn)$",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit always"
})

hl.window_rule({
    match = {
        class = "^(firefox)$",
        title = "(.* - YouTube)",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit always"
})

hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})

hl.config({
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    },
    -- Special workspace rules
    -- Floating rules
    -- Inhibit Idle
    -- windowrulev2 = immediate, class:^(gamescope)$
    -- Fix some dragging issues with XWayland
})

